### ISSUE TITLE
null pointer in getPredictivePosterior with n>1

### ISSUE THREAD

**Issue by rcabanasdepaz** [amidst/toolbox#35]
To reproduce this error run:
    eu.amidst.tutorials.huginsa2016.examples.DynamicModelInference.java  (branch develop)

when prediction posterior n steps ahead with n>1 I get:

Exception in thread "main" java.lang.NullPointerException
    at eu.amidst.dynamic.inference.FactoredFrontierForDBN.lambda$updateDynamicAssignmentTimeT$144(FactoredFrontierForDBN.java:356)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at eu.amidst.dynamic.inference.FactoredFrontierForDBN.updateDynamicAssignmentTimeT(FactoredFrontierForDBN.java:355)
    at eu.amidst.dynamic.inference.FactoredFrontierForDBN.moveWindow(FactoredFrontierForDBN.java:195)
    at eu.amidst.dynamic.inference.FactoredFrontierForDBN.getPredictivePosterior(FactoredFrontierForDBN.java:283)
    at eu.amidst.tutorials.huginsa2016.examples.DynamicModelInference.main(DynamicModelInference.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by andresmasegosa** [comment]
Fixed!
