### ISSUE TITLE
UndeclaredThrowableException in ParallelMLE2Test

### ISSUE THREAD

**Issue by rcabanasdepaz** [amidst/toolbox#45]
When running ParallelMLE2Test in examples module, the following Exception is thrown:

java.lang.reflect.UndeclaredThrowableException
    at eu.amidst.flinklink.core.learning.parametric.ParallelMaximumLikelihood2.updateModel(ParallelMaximumLikelihood2.java:126)
    at eu.amidst.flinklink.examples.ParallelMLE2.main(ParallelMLE2.java:65)
    at eu.amidst.flinklink.examples.ParallelMLE2Test.test(ParallelMLE2Test.java:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:255)
    at junit.framework.TestSuite.run(TestSuite.java:250)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.junit.runners.Suite.runChild(Suite.java:26)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
    at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply$mcV$sp(JobManager.scala:717)
    at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply(JobManager.scala:663)
    at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply(JobManager.scala:663)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8
    at eu.amidst.core.datastream.filereaders.arffFileReader.DataRowWeka.getValue(DataRowWeka.java:97)
    at eu.amidst.core.datastream.filereaders.DataInstanceFromDataRow.getValue(DataInstanceFromDataRow.java:58)
    at eu.amidst.core.datastream.DataInstance.getValue(DataInstance.java:60)
    at eu.amidst.core.exponentialfamily.EF_Normal_NormalParents.getSufficientStatistics(EF_Normal_NormalParents.java:179)
    at eu.amidst.core.exponentialfamily.EF_BayesianNetwork.lambda$getSufficientStatistics$26(EF_BayesianNetwork.java:208)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at eu.amidst.core.exponentialfamily.EF_BayesianNetwork.getSufficientStatistics(EF_BayesianNetwork.java:207)
    at eu.amidst.flinklink.core.learning.parametric.ParallelMaximumLikelihood2$SufficientSatisticsMAP.mapPartition(ParallelMaximumLikelihood2.java:195)
    at org.apache.flink.runtime.operators.MapPartitionDriver.run(MapPartitionDriver.java:98)
    at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:480)
    at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:345)
    at org.apache.flink.runtime.taskmanager.Task.run(Task.java:559)
    at java.lang.Thread.run(Thread.java:745)

**Comment by rcabanasdepaz** [comment]
In class ParallelMaximumLikelihood:

```
public double getLogMarginalProbability() {
    //TODO: temporal solution, the logMarginalProbability should be actually calculated.
    return Double.NaN;
    //throw new UnsupportedOperationException("Method not implemented yet");
}
```
