### ISSUE TITLE
ParallelMLExample in Flink and logging

### ISSUE THREAD

**Issue by jdevoo** [amidst/toolbox#92]
Hi! I am trying one of the examples in Flink pasted below. Somehow, after the call to updateModel, I am not able to obtain any logging information. Any ideas why?

```
public class ParallelMLExample {
    public static void main(String[] args) throws Exception {
        final ExecutionEnvironment env;

        //Set-up Flink session
        env = ExecutionEnvironment.getExecutionEnvironment();
        env.getConfig().disableSysoutLogging();
        Logger LOG = LoggerFactory.getLogger("ness.com.ParallelMLExample");

        //generate a random dataset
        DataFlink<DataInstance> dataFlink = new DataSetGenerator().generate(env, 1234, 1000, 5, 0);

        //Creates a DAG with the NaiveBayes structure for the random dataset
        DAG dag = DAGGenerator.getNaiveBayesStructure(dataFlink.getAttributes(), "DiscreteVar4");
        LOG.info(dag.toString());

        //Create the Learner object
        ParameterLearningAlgorithm learningAlgorithmFlink = new ParallelMaximumLikelihood();

        //Learning parameters
        learningAlgorithmFlink.setBatchSize(10);
        learningAlgorithmFlink.setDAG(dag);


        //Initialize the learning process
        learningAlgorithmFlink.initLearning();

        //Learn from the flink data
        LOG.info("BEFORE UPDATEMODEL");
        learningAlgorithmFlink.updateModel(dataFlink);
        LOG.info("AFTER UPDATEMODEL");

        //Print the learnt Bayes Net
        BayesianNetwork bn = learningAlgorithmFlink.getLearntBayesianNetwork();
        LOG.info(bn.toString());
    }
}
```

**Comment by andresmasegosa** [comment]
Hi,

Try to remove the line 
        env.getConfig().disableSysoutLogging();

and see if it works now.

**Comment by jdevoo** [comment]
Hello Andres! I had tried that but no luck. I am running the docker image of flink (1 taskmanager, 1 jobmanager) and had to switch to Log4j and LOG.info() calls instead of System.out.println() statements; there's still work required to get the stdout on the web console for docker images of flink.
I was wondering what behind updateModel can impact the context...

```
102735f2f6f471a1debadb994e8146ea has started.
2018-01-15 09:43:05,974 INFO  org.apache.flink.runtime.instance.InstanceManager             - Registered TaskManager at 22dc4bf15930 (akka.tcp://flink@22dc4bf15930:40219/user/taskmanager) as f57c19329bd2e82ae59b059ad313e9e5. Current number of registered hosts is 1. Current number of alive task slots is 2.
2018-01-15 09:43:55,997 INFO  ness.com.ParallelMLExample                                    - DAG
DiscreteVar0 has 1 parent(s): {DiscreteVar4}
DiscreteVar1 has 1 parent(s): {DiscreteVar4}
DiscreteVar2 has 1 parent(s): {DiscreteVar4}
DiscreteVar3 has 1 parent(s): {DiscreteVar4}
DiscreteVar4 has 0 parent(s): {}

2018-01-15 09:43:56,003 INFO  ness.com.ParallelMLExample                                    - BEFORE UPDATEMODEL
2018-01-15 09:43:56,067 INFO  org.apache.flink.api.java.ExecutionEnvironment                - The job has 2 registered types and 0 default Kryo serializers
2018-01-15 09:43:56,150 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: jobmanager.rpc.address, jobmanager
2018-01-15 09:43:56,150 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: jobmanager.rpc.port, 6123
2018-01-15 09:43:56,151 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: jobmanager.heap.mb, 1024
2018-01-15 09:43:56,151 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: taskmanager.heap.mb, 1024
2018-01-15 09:43:56,151 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: taskmanager.numberOfTaskSlots, 1
2018-01-15 09:43:56,152 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: taskmanager.memory.preallocate, false
2018-01-15 09:43:56,152 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: parallelism.default, 1
2018-01-15 09:43:56,152 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: jobmanager.web.port, 8081
2018-01-15 09:43:56,153 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: blob.server.port, 6124
2018-01-15 09:43:56,153 INFO  org.apache.flink.configuration.GlobalConfiguration            - Loading configuration property: query.server.port, 6125
2018-01-15 09:43:56,201 INFO  org.apache.flink.runtime.blob.BlobClient                      - Blob client connecting to akka://flink/user/jobmanager
2018-01-15 09:43:56,497 INFO  org.apache.flink.runtime.client.JobClient                     - Checking and uploading JAR files
2018-01-15 09:43:56,497 INFO  org.apache.flink.runtime.blob.BlobClient                      - Blob client connecting to akka://flink/user/jobmanager
2018-01-15 09:43:56,741 INFO  org.apache.flink.runtime.jobmanager.JobManager                - Submitting job d2be263cd01c037c57bb4aafb372bf2a (Flink Java Job at Mon Jan 15 09:43:56 UTC 2018).
2018-01-15 09:43:56,753 INFO  org.apache.flink.runtime.jobmanager.JobManager                - Using restart strategy NoRestartStrategy for d2be263cd01c037c57bb4aafb372bf2a.
2018-01-15 09:43:56,765 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Job recovers via failover strategy: full graph restart
2018-01-15 09:43:56,780 INFO  org.apache.flink.runtime.jobmanager.JobManager                - Running initialization on master for job Flink Java Job at Mon Jan 15 09:43:56 UTC 2018 (d2be263cd01c037c57bb4aafb372bf2a).
2018-01-15 09:43:56,792 INFO  org.apache.flink.runtime.jobmanager.JobManager                - Successfully ran initialization on master in 12 ms.
2018-01-15 09:43:56,819 INFO  org.apache.flink.runtime.jobmanager.JobManager                - Scheduling job d2be263cd01c037c57bb4aafb372bf2a (Flink Java Job at Mon Jan 15 09:43:56 UTC 2018).
2018-01-15 09:43:56,819 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Job Flink Java Job at Mon Jan 15 09:43:56 UTC 2018 (d2be263cd01c037c57bb4aafb372bf2a) switched from state CREATED to RUNNING.
2018-01-15 09:43:56,820 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - CHAIN DataSource (at sampleToDataFlink(BayesianNetworkSampler.java:89) (org.apache.flink.api.java.io.ParallelIteratorInputFormat)) -> FlatMap (FlatMap at sampleToDataFlink(BayesianNetworkSampler.java:90)) -> Map (Map at updateModel(ParallelMaximumLikelihood.java:100)) -> Reduce (Reduce at updateModel(ParallelMaximumLikelihood.java:102)) (1/1) (c4ef4f3e484761c2effa892fca733558) switched from CREATED to SCHEDULED.
2018-01-15 09:43:56,841 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - CHAIN DataSource (at sampleToDataFlink(BayesianNetworkSampler.java:89) (org.apache.flink.api.java.io.ParallelIteratorInputFormat)) -> FlatMap (FlatMap at sampleToDataFlink(BayesianNetworkSampler.java:90)) -> Map (Map at updateModel(ParallelMaximumLikelihood.java:100)) -> Reduce (Reduce at updateModel(ParallelMaximumLikelihood.java:102)) (1/1) (c4ef4f3e484761c2effa892fca733558) switched from SCHEDULED to DEPLOYING.
2018-01-15 09:43:56,843 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Deploying CHAIN DataSource (at sampleToDataFlink(BayesianNetworkSampler.java:89) (org.apache.flink.api.java.io.ParallelIteratorInputFormat)) -> FlatMap (FlatMap at sampleToDataFlink(BayesianNetworkSampler.java:90)) -> Map (Map at updateModel(ParallelMaximumLikelihood.java:100)) -> Reduce (Reduce at updateModel(ParallelMaximumLikelihood.java:102)) (1/1) (attempt #0) to 22dc4bf15930
2018-01-15 09:43:57,462 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - CHAIN DataSource (at sampleToDataFlink(BayesianNetworkSampler.java:89) (org.apache.flink.api.java.io.ParallelIteratorInputFormat)) -> FlatMap (FlatMap at sampleToDataFlink(BayesianNetworkSampler.java:90)) -> Map (Map at updateModel(ParallelMaximumLikelihood.java:100)) -> Reduce (Reduce at updateModel(ParallelMaximumLikelihood.java:102)) (1/1) (c4ef4f3e484761c2effa892fca733558) switched from DEPLOYING to RUNNING.
2018-01-15 09:43:57,910 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - DataSink (collect()) (1/1) (da682030935c925ce78e6859fa475350) switched from CREATED to SCHEDULED.
2018-01-15 09:43:57,912 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - DataSink (collect()) (1/1) (da682030935c925ce78e6859fa475350) switched from SCHEDULED to DEPLOYING.
2018-01-15 09:43:57,913 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Deploying DataSink (collect()) (1/1) (attempt #0) to 22dc4bf15930
2018-01-15 09:43:57,933 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - CHAIN DataSource (at sampleToDataFlink(BayesianNetworkSampler.java:89) (org.apache.flink.api.java.io.ParallelIteratorInputFormat)) -> FlatMap (FlatMap at sampleToDataFlink(BayesianNetworkSampler.java:90)) -> Map (Map at updateModel(ParallelMaximumLikelihood.java:100)) -> Reduce (Reduce at updateModel(ParallelMaximumLikelihood.java:102)) (1/1) (c4ef4f3e484761c2effa892fca733558) switched from RUNNING to FINISHED.
2018-01-15 09:43:57,996 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - DataSink (collect()) (1/1) (da682030935c925ce78e6859fa475350) switched from DEPLOYING to RUNNING.
2018-01-15 09:43:58,151 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - DataSink (collect()) (1/1) (da682030935c925ce78e6859fa475350) switched from RUNNING to FINISHED.
2018-01-15 09:43:58,161 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Job Flink Java Job at Mon Jan 15 09:43:56 UTC 2018 (d2be263cd01c037c57bb4aafb372bf2a) switched from state RUNNING to FINISHED.
```

**Comment by andresmasegosa** [comment]
This is the code behind updateModel()

        try {
            Configuration config = new Configuration();
            config.setString(BN_NAME, this.dag.getName());
            config.setBytes(EFBN_NAME, Serialization.serializeObject(efBayesianNetwork));

            DataSet<DataInstance> dataset = dataUpdate.getDataSet();
            this.sumSS = dataset.map(new SufficientSatisticsMAP())
                    .withParameters(config)
                    .reduce(new SufficientSatisticsReduce())
                    .collect().get(0);

            //Add the prior
            sumSS.sum(efBayesianNetwork.createInitSufficientStatistics());

            JobExecutionResult result = dataset.getExecutionEnvironment().getLastJobExecutionResult();

            numInstances = result.getAccumulatorResult(ParallelMaximumLikelihood.COUNTER_NAME+"_"+this.dag.getName());
            numInstances++;//Initial counts

        }catch(Exception ex){
            throw new UndeclaredThrowableException(ex);
        }

        return this.getLogMarginalProbability();

We just invoke basic Flink functionality. Nothing that may affect the logging behaviour. I have the impression that the problem can be on Flink side. You may post an issue on Flink GitHub to get some feedback. 

I'll leave this issue open yet.

**Comment by jdevoo** [comment]
I am still not able to figure this out. I had [posted to flink-user](http://mail-archives.apache.org/mod_mbox/flink-user/201801.mbox/%3C248feda4-1865-d966-560d-d847ae455895@data-artisans.com%3E) but still no luck. I could not locate AMIDST examples which use a Logger. My setup uses docker images of flink 1.4.0 - one started as taskmanager, one as jobmanager in cluster mode. The script that launches flink is flink-console.sh (start-foreground forced) which relies on log4j-console.properties. I am providing my own properties file which restricts output to my LOG output.
Somehow the call to the method above delegates work to the TM which breaks the Logger.
```
Creating flink_jobmanager_1  ... done
Creating flink_jobmanager_1  ...
Creating flink_taskmanager_1 ... done
Attaching to flink_jobmanager_1, flink_taskmanager_1
jobmanager_1   | Starting Job Manager
jobmanager_1   | config file:
jobmanager_1   | jobmanager.rpc.address: jobmanager
taskmanager_1  | Starting Task Manager
jobmanager_1   | jobmanager.rpc.port: 6123
taskmanager_1  | config file:
jobmanager_1   | jobmanager.heap.mb: 1024
jobmanager_1   | taskmanager.heap.mb: 1024
taskmanager_1  | jobmanager.rpc.address: jobmanager
jobmanager_1   | taskmanager.numberOfTaskSlots: 1
taskmanager_1  | jobmanager.rpc.port: 6123
jobmanager_1   | taskmanager.memory.preallocate: false
taskmanager_1  | jobmanager.heap.mb: 1024
jobmanager_1   | parallelism.default: 1
taskmanager_1  | taskmanager.heap.mb: 1024
jobmanager_1   | web.port: 8081
taskmanager_1  | taskmanager.numberOfTaskSlots: 2
jobmanager_1   | blob.server.port: 6124
taskmanager_1  | taskmanager.memory.preallocate: false
jobmanager_1   | query.server.port: 6125
taskmanager_1  | parallelism.default: 1
taskmanager_1  | web.port: 8081
jobmanager_1   | Starting jobmanager as a console application on host b6157929dcf7.
taskmanager_1  | blob.server.port: 6124
taskmanager_1  | query.server.port: 6125
taskmanager_1  | Starting taskmanager as a console application on host 75f00304194c.
jobmanager_1   | 2018-02-18 10:33:29,512 INFO  akka.event.slf4j.Slf4jLogger                                  - Slf4jLogger started
taskmanager_1  | 2018-02-18 10:33:30,435 INFO  akka.event.slf4j.Slf4jLogger                                  - Slf4jLogger started
jobmanager_1   | 2018-02-18 10:34:47,992 INFO  com.ness.ParallelMLExample                                    - DAG
jobmanager_1   | DiscreteVar0 has 1 parent(s): {DiscreteVar4}
jobmanager_1   | DiscreteVar1 has 1 parent(s): {DiscreteVar4}
jobmanager_1   | DiscreteVar2 has 1 parent(s): {DiscreteVar4}
jobmanager_1   | DiscreteVar3 has 1 parent(s): {DiscreteVar4}
jobmanager_1   | DiscreteVar4 has 0 parent(s): {}
jobmanager_1   |
jobmanager_1   | 2018-02-18 10:34:47,998 INFO  com.ness.ParallelMLExample                                    - ########## BEFORE UPDATEMODEL ##########
Gracefully stopping... (press Ctrl+C again to force)
```

**Comment by jdevoo** [comment]
still not working. Just tried with 0.7.0 and Flink 1.4.2 under Docker. No help from the Flink forum.
Is it related to [this](https://issues.apache.org/jira/browse/FLINK-7990) Flink issue? The docker compose file is below

```
version: "2.0"
services:
  jobmanager:
    image: flink
    expose:
      - 6123
    ports:
      - 8081:8081
    command: jobmanager
    volumes:
      - /home/jdevoo/playground/flink/shared:/root
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_CONF_DIR=/root
      - FLINK_ENV_JAVA_OPTS=-Dlog.file=/opt/flink/log/jobmanager.out

  taskmanager:
    image: flink
    expose:
      - 6121
      - 6122
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - /home/jdevoo/playground/flink/shared:/root
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_CONF_DIR=/root
      - FLINK_ENV_JAVA_OPTS=-Dlog.file=/opt/flink/log/taskmanager.out
```
and below the log output
```
jobmanager_1   | Starting Job Manager
jobmanager_1   | config file: 
jobmanager_1   | jobmanager.rpc.address: jobmanager
jobmanager_1   | jobmanager.rpc.port: 6123
jobmanager_1   | jobmanager.heap.mb: 1024
jobmanager_1   | taskmanager.heap.mb: 1024
jobmanager_1   | taskmanager.numberOfTaskSlots: 1
jobmanager_1   | taskmanager.memory.preallocate: false
jobmanager_1   | parallelism.default: 1
jobmanager_1   | web.port: 8081
jobmanager_1   | blob.server.port: 6124
jobmanager_1   | query.server.port: 6125
jobmanager_1   | Starting jobmanager as a console application on host a5a98db86564.
taskmanager_1  | Starting Task Manager
taskmanager_1  | config file: 
taskmanager_1  | jobmanager.rpc.address: jobmanager
taskmanager_1  | jobmanager.rpc.port: 6123
taskmanager_1  | jobmanager.heap.mb: 1024
taskmanager_1  | taskmanager.heap.mb: 1024
taskmanager_1  | taskmanager.numberOfTaskSlots: 4
taskmanager_1  | taskmanager.memory.preallocate: false
taskmanager_1  | parallelism.default: 1
taskmanager_1  | web.port: 8081
taskmanager_1  | blob.server.port: 6124
taskmanager_1  | query.server.port: 6125
taskmanager_1  | Starting taskmanager as a console application on host 53924b11ff2f.
jobmanager_1   | Slf4jLogger started
taskmanager_1  | Slf4jLogger started
taskmanager_1  | Could not load Queryable State Client Proxy. Probable reason: flink-queryable-state-runtime is not in the classpath. To enable Queryable State, please move the flink-queryable-state-runtime jar from the opt to the lib folder.
taskmanager_1  | Could not load Queryable State Server. Probable reason: flink-queryable-state-runtime is not in the classpath. To enable Queryable State, please move the flink-queryable-state-runtime jar from the opt to the lib folder.
jobmanager_1   | DAG
jobmanager_1   | DiscreteVar0 has 1 parent(s): {DiscreteVar4}
jobmanager_1   | DiscreteVar1 has 1 parent(s): {DiscreteVar4}
jobmanager_1   | DiscreteVar2 has 1 parent(s): {DiscreteVar4}
jobmanager_1   | DiscreteVar3 has 1 parent(s): {DiscreteVar4}
jobmanager_1   | DiscreteVar4 has 0 parent(s): {}
jobmanager_1   | 
jobmanager_1   | ########## BEFORE UPDATEMODEL ##########
taskmanager_1  | The operator name DataSource (at sampleToDataFlink(BayesianNetworkSampler.java:99) (org.apache.flink.api.java.io.ParallelIteratorInputFormat)) exceeded the 80 characters length limit and was truncated.
```

**Comment by andresmasegosa** [comment]
Sorry to hear that @jdevoo. I'll let you know if we find something.
